# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['C:\\Users\\anghe\\OneDrive\\Desktop\\NUEVA INT'],  # Cambia esta ruta si es necesario
    binaries=[],
    datas=[
        ('data/razas/craneo.png', 'data/razas'),
        ('data/razas/druida.png', 'data/razas'),
        ('data/razas/enano.png', 'data/razas'),
        ('data/razas/mago.png', 'data/razas'),
        ('data/razas/silueta-de-cuerpo-humano-de-pie.png', 'data/razas'),
        ('data/razas/yeti.png', 'data/razas'),
        ('data/razas/orco.gif', 'data/razas'),
        ('data/iconos/agregar-usuario.png', 'data/iconos'),
        ('data/iconos/analisis.png', 'data/iconos'),
        ('data/iconos/barajar.png', 'data/iconos'),
        ('data/iconos/casino.png', 'data/iconos'),
        ('data/iconos/crear.png', 'data/iconos'),
        ('data/iconos/dado (1).png', 'data/iconos'),
        ('data/iconos/dado (2).png', 'data/iconos'),
        ('data/iconos/dado (3).png', 'data/iconos'),
        ('data/iconos/dado.png', 'data/iconos'),
        ('data/iconos/dados (1).png', 'data/iconos'),
        ('data/iconos/dados (2).png', 'data/iconos'),
        ('data/iconos/dados-d20.png', 'data/iconos'),
        ('data/iconos/dados.png', 'data/iconos'),
        ('data/iconos/desplazarse-viejo.png', 'data/iconos'),
        ('data/iconos/exportacion-de-archivos.png', 'data/iconos'),
        ('data/iconos/forjar.png', 'data/iconos'),
        ('data/iconos/guardar-el-archivo.png', 'data/iconos'),
        ('data/iconos/iniciar-sesion.png', 'data/iconos'),
        ('data/iconos/juego-de-rol (1).png', 'data/iconos'),
        ('data/iconos/juego-de-rol.png', 'data/iconos'),
        ('data/iconos/libro-de-historia.png', 'data/iconos'),
        ('data/iconos/lista-de-verificacion.png', 'data/iconos'),
        ('data/iconos/lupa.png', 'data/iconos'),
        ('data/iconos/maestro.png', 'data/iconos'),
        ('data/iconos/mejoramiento.png', 'data/iconos'),
        ('data/iconos/pareja.png', 'data/iconos'),
        ('data/iconos/personaje.png', 'data/iconos'),
        ('data/iconos/procesamiento-de-datos.png', 'data/iconos'),
        ('data/iconos/prohibido.png', 'data/iconos'),
        ('data/iconos/registrarse.png', 'data/iconos'),
        ('data/iconos/victoria.png', 'data/iconos'),
        ('data/iconos/corazon.gif', 'data/iconos'),
        ('data/iconos/esqueleto.gif', 'data/iconos'),
        ('data/iconos/ruta.gif', 'data/iconos'),
        ('data/armas/espada.png', 'data/armas'),
        ('data/armas/espadas.png', 'data/armas'),
        ('data/armas/hacha.png', 'data/armas'),
        ('data/armas/juego-de-rol.png', 'data/armas'),
        ('data/armas/mago.png', 'data/armas'),
        ('data/armas/tiro-al-arco.png', 'data/armas'),
        ('data/gif/esqueleto.gif', 'data/gif'),
        ('data/gif/revive.gif', 'data/gif')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Cambiar a True si necesitas la consola
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
